name: Build and publish Connectors

on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:
    inputs:
      airbyte_ci_binary_url:
        description: "URL to the airbyte-ci binary to use for the action. If not provided, the action will use the latest release of airbyte-ci."
        default: "https://connectors.airbyte.com/airbyte-ci/releases/ubuntu/latest/airbyte-ci"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        connector:
          # - name: source-odata
          #   tag: 0.1.6-alpha
          # - name: source-postgres
          #   tag: 0.1.4-alpha
          # - name: source-mssql
          #   tag: 0.1.0
          # - name: source-file
          #   tag: 0.1.0
          # - name: destination-mssql
          #   tag: 0.1.0
          # - name: destination-postgres
          #   tag: 0.1.0
          - name: destination-s3
            tag: 0.1.0

    steps:
      - name: Checkout Airbyte
        uses: actions/checkout@v4

      - name: Build ${{ matrix.connector.name }}
        uses: ./.github/actions/run-airbyte-ci
        with:
          context: "manual"
          subcommand: "connectors --name=${{ matrix.connector.name }} build --tag ${{ matrix.connector.tag }}"
          airbyte_ci_binary_url: ${{ github.event.inputs.airbyte_ci_binary_url }}
          max_attempts: 2
