name: Sync Repos via PR

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Sync changes via PR
        run: |
          # Set git identity
          git config --global user.email "romario.silva@syniti.com"
          git config --global user.name "romario-syniti"

          # Clone destination repo
          git clone https://${{ env.DESTINATION_ORG_NAME }}:${{ secrets.PAT }}@github.com/${{ env.DESTINATION_ORG_NAME }}/airbyte.git
          cd airbyte

          # Add source repo as remote
          git remote add ${{ env.ORIGINAL_REPO_NAME }} https://${{ env.SOURCE_ORG_NAME }}:${{ secrets.PAT }}@github.com/${{ env.SOURCE_ORG_NAME }}/${{ env.ORIGINAL_REPO_NAME }}.git
          git remote update

          # Create new branch with timestamp
          BRANCH_NAME="sync-$(date +%Y%m%d-%H%M%S)"
          git checkout -b $BRANCH_NAME

          # Merge changes from source
          git merge ${{ env.ORIGINAL_REPO_NAME }}/master --no-ff -m "Sync changes from ${{ env.ORIGINAL_REPO_NAME }}"

          # Push to new branch
          git push origin $BRANCH_NAME

          # Create PR using GitHub CLI
          gh pr create \
            --title "Sync changes from ${{ env.ORIGINAL_REPO_NAME }} (automated)" \
            --body "Automated sync of changes from source repository." \
            --base main \
            --head $BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          ORIGINAL_REPO_NAME: ${{ github.event.repository.name }}
          SOURCE_ORG_NAME: romario-syniti
          DESTINATION_ORG_NAME: ${{ secrets.ORG }}
