name: Sync Repos via PR

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      source_branch:
        description: "Source branch to sync from"
        required: false
        default: "master"
      destination_branch:
        description: "Destination branch to sync to"
        required: false
        default: "master"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Setup GitHub CLI
        run: |
          gh auth login --with-token <<< "${{ secrets.PAT }}"
          gh auth status

      - name: Sync changes via PR
        run: |
          # Set git identity
          git config --global user.email "romario.silva@syniti.com"
          git config --global user.name "romario-syniti"

          # Clone destination repo
          gh repo clone ${{ env.DESTINATION_ORG_NAME }}/airbyte
          cd airbyte

          # Update origin URL to include credentials
          git remote set-url origin https://${{ secrets.PAT }}@github.com/${{ env.SOURCE_ORG_NAME }}/${{ env.ORIGINAL_REPO_NAME }}.git

          # Add source repo as remote
          git remote add ${{ env.ORIGINAL_REPO_NAME }} https://${{ secrets.PAT }}@github.com/${{ env.SOURCE_ORG_NAME }}/${{ env.ORIGINAL_REPO_NAME }}.git
          git remote update

          # Create new branch with timestamp
          BRANCH_NAME="sync-$(date +%Y%m%d-%H%M%S)"
          git checkout -b $BRANCH_NAME

          # Attempt merge but continue even if conflicts exist
          git merge ${{ env.ORIGINAL_REPO_NAME }}/${{ github.event.inputs.source_branch || 'master' }} --no-ff -m "Sync changes from ${{ env.ORIGINAL_REPO_NAME }}" || true

          # Push branch (even with conflicts)
          git push origin $BRANCH_NAME

          # Create PR with note about conflicts
          gh pr create \
            --title "Sync changes from ${{ env.ORIGINAL_REPO_NAME }} (automated)" \
            --body "Automated sync of changes from source repository. **NOTE:** This PR has merge conflicts that need to be resolved manually." \
            --base ${{ github.event.inputs.destination_branch || 'main' }} \
            --head $BRANCH_NAME

        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          ORIGINAL_REPO_NAME: ${{ github.event.repository.name }}
          SOURCE_ORG_NAME: romario-syniti
          DESTINATION_ORG_NAME: ${{ secrets.ORG }}
